site_name: CRISP Controllers - Learning Systems Lab
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Setting up a robot that is not available in the demos: new_robot_setup.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Poppins
    # text: Montserrat
    code: Source Code Pro
  features:
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  # - mkdoxy:
  #     projects:
  #       crisp_controllers: # name of project must be alphanumeric + numbers (without spaces)
  #         src-dirs: crisp_controllers
  #         full-doc: True # if you want to generate full documentation
  #         doxy-cfg: # standard doxygen configuration (key: value)
  #           FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
  #           RECURSIVE: True # recursive search in source directorie



extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/utiasDSL/crisp_controllers

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true 
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css
