name: ROS 2 CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths . --ignore-src -y

      - name: Build
        run: |
          colcon build --event-handlers console_direct+

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

